# Dapr Secrets Component: Kubernetes Secrets (Local Development)
# Purpose: Retrieve secrets from Kubernetes for local Minikube deployment
# Environment: Minikube (local development only)
# Security: Base64 encoding (NOT encrypted), suitable for local dev only
# Date: 2025-12-29

---
# IMPORTANT: Security Notice
# ⚠️ Kubernetes Secrets are NOT encrypted (only Base64 encoded)
# ⚠️ Use ONLY for local development (Minikube)
# ⚠️ Production MUST use cloud-native vaults (OCI Vault, Azure Key Vault, Google Secret Manager)

---
# Kubernetes Secrets Store Component

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore
  namespace: default
spec:
  type: secretstores.kubernetes
  version: v1
  metadata: []  # No additional configuration required

---
# Kubernetes Secret Creation (Manual)

secrets_to_create:
  database_secrets:
    description: Neon PostgreSQL connection string
    creation_command: |
      kubectl create secret generic database-secrets \
        --from-literal=DATABASE_URL="host=neon-db.neon.tech port=5432 user=postgres password=YOUR_PASSWORD dbname=todo_db sslmode=require" \
        --namespace=default

    usage_in_app: |
      # Retrieve secret via Dapr Secrets API
      import httpx

      async def get_database_url():
          response = await httpx.get(
              "http://localhost:3500/v1.0/secrets/secretstore/database-secrets/DATABASE_URL"
          )
          return response.json()  # Returns {"DATABASE_URL": "host=neon-db..."}

  kafka_secrets:
    description: Kafka broker addresses (for cloud deployments)
    creation_command: |
      kubectl create secret generic kafka-secrets \
        --from-literal=KAFKA_BROKERS="kafka:9092" \
        --namespace=default

  smtp_secrets:
    description: SMTP credentials for email notifications
    creation_command: |
      kubectl create secret generic smtp-secrets \
        --from-literal=SMTP_HOST="smtp.gmail.com" \
        --from-literal=SMTP_PORT="587" \
        --from-literal=SMTP_USERNAME="noreply@example.com" \
        --from-literal=SMTP_PASSWORD="YOUR_APP_PASSWORD" \
        --namespace=default

  better_auth_secrets:
    description: Better Auth JWT secret for authentication
    creation_command: |
      kubectl create secret generic better-auth-secrets \
        --from-literal=BETTER_AUTH_SECRET="$(openssl rand -hex 32)" \
        --namespace=default

---
# Application Usage

application_usage:
  retrieving_secret:
    description: Retrieve secret via Dapr Secrets API
    python_example: |
      import httpx

      async def get_secret(secret_store: str, secret_name: str, secret_key: str):
          """Retrieve secret from Dapr Secrets Store"""
          response = await httpx.get(
              f"http://localhost:3500/v1.0/secrets/{secret_store}/{secret_name}/{secret_key}"
          )

          if response.status_code == 200:
              secret_data = response.json()
              return secret_data[secret_key]
          else:
              raise Exception(f"Failed to retrieve secret: {response.text}")

      # Example usage
      database_url = await get_secret("secretstore", "database-secrets", "DATABASE_URL")
      smtp_password = await get_secret("secretstore", "smtp-secrets", "SMTP_PASSWORD")

  environment_variable_approach:
    description: Alternative approach using environment variables with secretKeyRef
    kubernetes_deployment: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: task-service
      spec:
        template:
          spec:
            containers:
            - name: task-service
              image: todo-backend:latest
              env:
              - name: DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: database-secrets
                    key: DATABASE_URL
              - name: SMTP_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: smtp-secrets
                    key: SMTP_PASSWORD

---
# Secret Rotation

secret_rotation:
  strategy: Manual rotation for local development
  steps:
    - Update secret value: kubectl edit secret database-secrets
    - Restart pods to pick up new value: kubectl rollout restart deployment/task-service
    - Verify new secret loaded: kubectl logs <pod-name> | grep "Connected to database"

  production_rotation:
    note: Use cloud-native vault auto-rotation (OCI Vault, Azure Key Vault, Google Secret Manager)
    frequency: Rotate every 90 days or after security incident

---
# Security Best Practices

security_best_practices:
  local_development:
    - ✅ Use Kubernetes Secrets for local Minikube (simple, fast iteration)
    - ✅ Store secrets in .env.local (git-ignored file) for local testing
    - ✅ Never commit secrets to version control (.gitignore database-secrets.yaml)
    - ✅ Use dummy/placeholder values for non-sensitive local secrets

  production:
    - ❌ NEVER use Kubernetes Secrets in production (not encrypted)
    - ✅ Use cloud-native vaults (OCI Vault, Azure Key Vault, Google Secret Manager)
    - ✅ Enable automatic secret rotation (90-day rotation policy)
    - ✅ Use Dapr Secrets abstraction (easy to swap Kubernetes→Vault)
    - ✅ Audit secret access (who accessed which secret when)

---
# Migration to Production Vault

migration_path:
  description: How to migrate from Kubernetes Secrets (local) to OCI Vault (production)
  steps:
    - step: 1
      description: Create secrets in OCI Vault
      command: |
        # Create secret in OCI Vault using OCI CLI
        oci vault secret create-base64 \
          --compartment-id ocid1.compartment.oc1... \
          --secret-name DATABASE_URL \
          --vault-id ocid1.vault.oc1... \
          --key-id ocid1.key.oc1... \
          --secret-content-content "$(echo 'host=neon-db...' | base64)"

    - step: 2
      description: Update Dapr Secrets component to use OCI Vault
      yaml: |
        apiVersion: dapr.io/v1alpha1
        kind: Component
        metadata:
          name: secretstore
          namespace: production
        spec:
          type: secretstores.oci.vault
          version: v1
          metadata:
            - name: vaultOcid
              value: "ocid1.vault.oc1..."
            - name: compartmentOcid
              value: "ocid1.compartment.oc1..."

    - step: 3
      description: Application code remains unchanged (Dapr abstraction)
      note: Same Dapr Secrets API works with both Kubernetes Secrets and OCI Vault

---
# Troubleshooting

troubleshooting:
  secret_not_found:
    problem: "ERROR: secret 'database-secrets' not found"
    diagnosis: |
      # List all secrets in namespace
      kubectl get secrets -n default

      # Describe secret
      kubectl describe secret database-secrets -n default

    solutions:
      - Create secret using kubectl create secret command (see above)
      - Verify namespace matches (default vs production)
      - Check secret name spelling (case-sensitive)

  permission_denied:
    problem: "ERROR: permission denied to access secret"
    diagnosis: |
      # Check service account permissions
      kubectl get serviceaccount default -n default -o yaml

      # Check RBAC role bindings
      kubectl get rolebindings -n default

    solutions:
      - Grant read access to secrets: kubectl create rolebinding secret-reader --role=secret-reader --serviceaccount=default:default
      - Use Dapr with proper service account annotations

  secret_value_empty:
    problem: Retrieved secret value is empty or null
    diagnosis: |
      # Decode secret value
      kubectl get secret database-secrets -o jsonpath='{.data.DATABASE_URL}' | base64 -d

    solutions:
      - Verify secret was created with correct key name (DATABASE_URL vs database_url)
      - Check Base64 encoding: echo "value" | base64
      - Recreate secret if value is corrupted

---
# Related Documents

related_documents:
  - name: secretstore-oci-vault.yaml
    path: ./secretstore-oci-vault.yaml
    description: Production Dapr Secrets component for OCI Vault

  - name: research.md
    path: ../research.md
    description: Technical research on secrets management strategy

  - name: Dapr Kubernetes Secrets
    url: https://docs.dapr.io/reference/components-reference/supported-secret-stores/kubernetes-secret-store/
    description: Official Dapr Kubernetes Secrets Store documentation
