# Dapr Secrets Component: OCI Vault (Production)
# Purpose: Retrieve secrets from Oracle Cloud Infrastructure Vault for production deployment
# Environment: OKE (Oracle Kubernetes Engine) production environment
# Security: Encrypted at rest, automatic rotation, audit logging
# Date: 2025-12-29

---
# OCI Vault Secrets Store Component

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore
  namespace: production
spec:
  type: secretstores.oci.vault
  version: v1
  metadata:
    # OCI Vault Configuration
    - name: vaultOcid
      value: "ocid1.vault.oc1.iad.EXAMPLE"  # Replace with actual Vault OCID

    - name: compartmentOcid
      value: "ocid1.compartment.oc1..EXAMPLE"  # Replace with actual Compartment OCID

    # Authentication (uses OKE workload identity or instance principal)
    - name: authType
      value: "instance_principal"  # Automatic authentication for OKE pods

    # Optional: Specific region (defaults to pod region)
    # - name: region
    #   value: "us-ashburn-1"

---
# OCI Vault Secret Creation

secrets_creation:
  prerequisites:
    - OCI account with Vault service enabled
    - OCI CLI installed and configured
    - Vault created in OCI Console or via Terraform

  create_vault:
    description: Create OCI Vault using OCI CLI
    command: |
      # Create Vault
      oci kms management vault create \
        --compartment-id ocid1.compartment.oc1..EXAMPLE \
        --display-name "todo-app-production-vault" \
        --vault-type DEFAULT

      # Create Master Encryption Key
      oci kms management key create \
        --compartment-id ocid1.compartment.oc1..EXAMPLE \
        --display-name "todo-app-master-key" \
        --key-shape '{"algorithm":"AES","length":32}' \
        --management-endpoint "https://xxx.kms.us-ashburn-1.oraclecloud.com"

  create_secret_database_url:
    description: Store Neon PostgreSQL connection string in OCI Vault
    command: |
      # Create secret for DATABASE_URL
      oci vault secret create-base64 \
        --compartment-id ocid1.compartment.oc1..EXAMPLE \
        --secret-name DATABASE_URL \
        --vault-id ocid1.vault.oc1.iad.EXAMPLE \
        --key-id ocid1.key.oc1.iad.EXAMPLE \
        --secret-content-content "$(echo 'host=neon-db.neon.tech port=5432 user=postgres password=PRODUCTION_PASSWORD dbname=todo_db sslmode=require' | base64)"

  create_secret_smtp_password:
    description: Store SMTP password in OCI Vault
    command: |
      # Create secret for SMTP_PASSWORD
      oci vault secret create-base64 \
        --compartment-id ocid1.compartment.oc1..EXAMPLE \
        --secret-name SMTP_PASSWORD \
        --vault-id ocid1.vault.oc1.iad.EXAMPLE \
        --key-id ocid1.key.oc1.iad.EXAMPLE \
        --secret-content-content "$(echo 'PRODUCTION_SMTP_PASSWORD' | base64)"

  create_secret_kafka_brokers:
    description: Store Redpanda Cloud broker addresses in OCI Vault
    command: |
      # Create secret for KAFKA_BROKERS
      oci vault secret create-base64 \
        --compartment-id ocid1.compartment.oc1..EXAMPLE \
        --secret-name KAFKA_BROKERS \
        --vault-id ocid1.vault.oc1.iad.EXAMPLE \
        --key-id ocid1.key.oc1.iad.EXAMPLE \
        --secret-content-content "$(echo 'serverless-abcd1234.redpanda.cloud:9092' | base64)"

  create_secret_better_auth:
    description: Store Better Auth JWT secret in OCI Vault
    command: |
      # Generate secure random secret
      BETTER_AUTH_SECRET=$(openssl rand -hex 32)

      # Create secret for BETTER_AUTH_SECRET
      oci vault secret create-base64 \
        --compartment-id ocid1.compartment.oc1..EXAMPLE \
        --secret-name BETTER_AUTH_SECRET \
        --vault-id ocid1.vault.oc1.iad.EXAMPLE \
        --key-id ocid1.key.oc1.iad.EXAMPLE \
        --secret-content-content "$(echo $BETTER_AUTH_SECRET | base64)"

---
# OKE Workload Identity Configuration

workload_identity:
  description: Grant OKE pods permission to access OCI Vault secrets
  steps:
    - step: 1
      description: Create IAM policy for OKE workload identity
      oci_cli: |
        # Create dynamic group for OKE pods
        oci iam dynamic-group create \
          --name "todo-app-oke-pods" \
          --description "OKE pods for Todo application" \
          --matching-rule "ALL {resource.type='cluster',resource.compartment.id='ocid1.compartment.oc1..EXAMPLE'}"

        # Create IAM policy to allow secret reading
        oci iam policy create \
          --compartment-id ocid1.compartment.oc1..EXAMPLE \
          --name "todo-app-vault-read-policy" \
          --description "Allow OKE pods to read secrets from Vault" \
          --statements '["Allow dynamic-group todo-app-oke-pods to read secret-bundles in compartment id ocid1.compartment.oc1..EXAMPLE"]'

    - step: 2
      description: Annotate Kubernetes service account for workload identity
      kubernetes_yaml: |
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: todo-app-sa
          namespace: production
          annotations:
            oci.oraclecloud.com/compartment-ocid: "ocid1.compartment.oc1..EXAMPLE"

    - step: 3
      description: Use service account in pod deployment
      kubernetes_yaml: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: task-service
          namespace: production
        spec:
          template:
            spec:
              serviceAccountName: todo-app-sa
              containers:
              - name: task-service
                image: todo-backend:latest

---
# Application Usage

application_usage:
  retrieving_secret:
    description: Retrieve secret via Dapr Secrets API (same as Kubernetes Secrets)
    python_example: |
      import httpx

      async def get_secret(secret_store: str, secret_name: str):
          """Retrieve secret from Dapr Secrets Store (OCI Vault)"""
          response = await httpx.get(
              f"http://localhost:3500/v1.0/secrets/{secret_store}/{secret_name}"
          )

          if response.status_code == 200:
              secret_data = response.json()
              return secret_data  # Returns {"DATABASE_URL": "host=neon-db...", ...}
          else:
              raise Exception(f"Failed to retrieve secret: {response.text}")

      # Example usage (same code works for Kubernetes Secrets and OCI Vault)
      database_secrets = await get_secret("secretstore", "DATABASE_URL")
      database_url = database_secrets["DATABASE_URL"]

---
# Secret Rotation

secret_rotation:
  automatic_rotation:
    description: OCI Vault supports automatic secret rotation
    configuration: |
      # Enable automatic rotation (90-day rotation)
      oci vault secret update \
        --secret-id ocid1.vaultsecret.oc1.iad.EXAMPLE \
        --rotation-config '{"targetSystemDetails":{"targetSystemType":"FUNCTION"},"isScheduledRotationEnabled":true,"rotationInterval":"P90D"}'

  manual_rotation:
    steps:
      - step: 1
        description: Create new secret version in OCI Vault
        command: |
          # Update secret with new value
          oci vault secret update-base64 \
            --secret-id ocid1.vaultsecret.oc1.iad.EXAMPLE \
            --secret-content-content "$(echo 'NEW_DATABASE_PASSWORD' | base64)"

      - step: 2
        description: Restart pods to pick up new secret (Dapr caches secrets)
        command: |
          kubectl rollout restart deployment/task-service -n production

      - step: 3
        description: Verify new secret loaded
        command: |
          kubectl logs -n production <pod-name> | grep "Connected to database"

---
# Monitoring and Audit

monitoring:
  audit_logging:
    description: OCI Vault provides audit logs for all secret access
    log_location: OCI Audit service (accessible via OCI Console or API)
    log_retention: 90 days (configurable)

    query_secret_access: |
      # Query OCI Audit logs for secret access
      oci audit event list \
        --compartment-id ocid1.compartment.oc1..EXAMPLE \
        --start-time "2025-12-01T00:00:00Z" \
        --end-time "2025-12-31T23:59:59Z" \
        --query "data[?\"event-name\"=='ReadSecretBundle'].{time:\"event-time\",user:\"identity.principal-name\",secret:\"request.resource-path\"}"

  alerting:
    - name: Unauthorized Secret Access
      condition: Audit log shows secret access from unknown principal
      severity: critical
      action: Alert security team

    - name: Secret Rotation Overdue
      condition: Secret age exceeds 90 days
      severity: warning
      action: Rotate secret manually

---
# Cost Optimization

cost_optimization:
  oci_vault_pricing:
    description: OCI Vault pricing (as of 2025)
    vault_cost: $1.00/vault/month
    key_cost: $1.00/key/month
    secret_versions: $0.00/version (first 500 versions free, then $0.05/version)
    api_calls: Free (no charge for secret retrieval API calls)

  cost_estimate_phase_v:
    - 1 Vault: $1.00/month
    - 1 Master Key: $1.00/month
    - 5 Secrets (DATABASE_URL, SMTP_PASSWORD, KAFKA_BROKERS, BETTER_AUTH_SECRET, REDPANDA_CERT): $0.00/month
    - Total: $2.00/month

  comparison_with_alternatives:
    - OCI Vault: $2.00/month
    - Azure Key Vault: $0.03/10,000 operations ($5-10/month typical)
    - Google Secret Manager: $0.06/10,000 operations ($5-10/month typical)
    - HashiCorp Vault (self-hosted): Free (but requires infrastructure and maintenance)

---
# Troubleshooting

troubleshooting:
  permission_denied:
    problem: "ERROR: permission denied to read secret from OCI Vault"
    diagnosis: |
      # Check IAM policy
      oci iam policy list --compartment-id ocid1.compartment.oc1..EXAMPLE

      # Verify dynamic group includes OKE cluster
      oci iam dynamic-group get --dynamic-group-id ocid1.dynamicgroup.oc1..EXAMPLE

    solutions:
      - Verify IAM policy allows "read secret-bundles in compartment"
      - Check dynamic group matching rule includes OKE cluster OCID
      - Ensure service account has correct OCI annotation

  secret_not_found:
    problem: "ERROR: secret 'DATABASE_URL' not found in OCI Vault"
    diagnosis: |
      # List all secrets in Vault
      oci vault secret list \
        --compartment-id ocid1.compartment.oc1..EXAMPLE \
        --vault-id ocid1.vault.oc1.iad.EXAMPLE

    solutions:
      - Verify secret name matches (case-sensitive)
      - Check secret is in correct Vault and compartment
      - Ensure secret state is ACTIVE (not PENDING_DELETION or DELETED)

  vault_unavailable:
    problem: "ERROR: unable to connect to OCI Vault"
    diagnosis: |
      # Check Vault status
      oci kms management vault get --vault-id ocid1.vault.oc1.iad.EXAMPLE

      # Test network connectivity from OKE
      kubectl run test-pod --image=curlimages/curl --rm -it -- curl -v https://vaults.us-ashburn-1.oci.oraclecloud.com

    solutions:
      - Verify Vault is in ACTIVE state (not CREATING or DELETING)
      - Check network policies allow OKE→OCI Vault traffic
      - Ensure correct region in Dapr component metadata

---
# Migration Path from Kubernetes Secrets

migration_checklist:
  - step: 1
    description: Create OCI Vault and secrets
    status: pending

  - step: 2
    description: Grant OKE pods permission via IAM policy
    status: pending

  - step: 3
    description: Update Dapr Secrets component to use OCI Vault
    yaml_change: |
      # Before (Kubernetes Secrets)
      type: secretstores.kubernetes

      # After (OCI Vault)
      type: secretstores.oci.vault
      metadata:
        - name: vaultOcid
          value: "ocid1.vault.oc1.iad.EXAMPLE"

  - step: 4
    description: Deploy updated Dapr component to production
    command: kubectl apply -f secretstore-oci-vault.yaml -n production
    status: pending

  - step: 5
    description: Restart pods to pick up new Dapr component
    command: kubectl rollout restart deployment/task-service -n production
    status: pending

  - step: 6
    description: Verify secret retrieval from OCI Vault
    command: kubectl logs -n production <pod-name> -c daprd | grep "Loaded secrets component"
    status: pending

  - step: 7
    description: Delete old Kubernetes Secrets (cleanup)
    command: kubectl delete secret database-secrets smtp-secrets -n production
    status: pending

---
# Related Documents

related_documents:
  - name: secretstore-kubernetes.yaml
    path: ./secretstore-kubernetes.yaml
    description: Local development Dapr Secrets component (Kubernetes Secrets)

  - name: research.md
    path: ../research.md
    description: Technical research on secrets management strategy (cloud vaults)

  - name: OCI Vault Documentation
    url: https://docs.oracle.com/en-us/iaas/Content/KeyManagement/home.htm
    description: Official Oracle Cloud Infrastructure Vault documentation

  - name: Dapr OCI Vault Secrets
    url: https://docs.dapr.io/reference/components-reference/supported-secret-stores/oci-vault/
    description: Official Dapr OCI Vault Secrets Store documentation
