apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-pubsub
  namespace: default
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    # Kafka broker configuration
    - name: brokers
      value: "kafka:9092"  # Minikube: kafka service, Cloud: update with broker URLs
    - name: consumerGroup
      value: "phase5-consumer-group"
    - name: clientId
      value: "phase5-client"
    - name: authType
      value: "none"  # Minikube: no auth, Cloud: use "sasl_plaintext" or "sasl_ssl"
    # Cloud authentication (uncomment for production)
    # - name: saslUsername
    #   secretKeyRef:
    #     name: kafka-credentials
    #     key: username
    # - name: saslPassword
    #   secretKeyRef:
    #     name: kafka-credentials
    #     key: password
    # - name: saslMechanism
    #   value: "PLAIN"

    # Topic configuration (topics created manually via create-kafka-topics.sh)
    # Topics: task-events, reminders, task-updates
    # Partitions: 12 per topic (for user_id partitioning)
    # Retention: 7 days (Minikube), 30 days (Cloud)

    # Consumer configuration
    - name: maxMessageBytes
      value: "1048576"  # 1MB max message size
    - name: consumeRetryInterval
      value: "200ms"  # Retry interval for failed messages

    # Producer configuration
    - name: enableIdempotence
      value: "true"  # Enable idempotent producer (exactly-once delivery)
    - name: acks
      value: "all"  # Wait for all replicas to acknowledge
    - name: compressionType
      value: "snappy"  # Enable compression for network efficiency

    # Partitioning strategy
    - name: partitionScheme
      value: "hash"  # Hash-based partitioning
    # Note: user_id will be included in event payload for partitioning
    # Kafka will hash user_id to determine partition (ensures ordering per user)

scopes:
  - backend
  - recurring-task-service
  - notification-service
  - audit-service
