# Dapr Secrets Store component for OCI Vault
# Retrieves secrets securely from Oracle Cloud Infrastructure Vault

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: oci-vault-secrets
  namespace: default
spec:
  type: secretstores.oci.vault
  version: v1
  metadata:
    # OCI Vault OCID (from OCI Console → Security → Vault)
    - name: vaultOcid
      value: "<OCI_VAULT_OCID>"  # e.g., "ocid1.vault.oc1.iad.xxxxxxxxx"

    # Compartment OCID where secrets are stored
    - name: compartmentOcid
      value: "<COMPARTMENT_OCID>"

    # OCI Region
    - name: region
      value: "<OCI_REGION>"  # e.g., "us-ashburn-1"

    # Authentication method (instance principal for pods running in OKE)
    - name: authType
      value: "instance"  # Use instance principal authentication

    # Alternative: Use API key authentication
    # - name: authType
    #   value: "api_key"
    # - name: tenancyOcid
    #   value: "<TENANCY_OCID>"
    # - name: userOcid
    #   value: "<USER_OCID>"
    # - name: fingerprint
    #   value: "<API_KEY_FINGERPRINT>"
    # - name: privateKey
    #   secretKeyRef:
    #     name: oci-api-key
    #     key: private_key

  # Scope to specific app IDs
  scopes:
    - backend
    - recurring-task-service
    - notification-service
