apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: oci-vault
  namespace: default
spec:
  type: secretstores.oci.vault
  version: v1
  metadata:
    # Oracle Cloud Infrastructure (OCI) Vault configuration (for OKE deployment)

    # OCI Vault parameters
    - name: vaultID
      value: "ocid1.vault.oc1...<vault-ocid>"  # Replace with actual OCI Vault OCID
    - name: compartmentID
      value: "ocid1.compartment.oc1...<compartment-ocid>"  # Replace with actual compartment OCID

    # OCI authentication (using instance principal for OKE)
    - name: authType
      value: "instancePrincipal"  # Use instance principal for OKE pods
    # Alternative: Use API key authentication
    # - name: authType
    #   value: "apiKey"
    # - name: tenancyOCID
    #   value: "ocid1.tenancy.oc1...<tenancy-ocid>"
    # - name: userOCID
    #   value: "ocid1.user.oc1...<user-ocid>"
    # - name: fingerprint
    #   value: "<api-key-fingerprint>"
    # - name: privateKey
    #   secretKeyRef:
    #     name: oci-credentials
    #     key: private-key

    # Region configuration
    - name: region
      value: "us-ashburn-1"  # Replace with OKE cluster region

    # Secrets stored in OCI Vault:
    # - database-credentials/connection-string: PostgreSQL connection string
    # - kafka-credentials/brokers: Kafka broker URLs (Redpanda Cloud)
    # - kafka-credentials/username: Kafka SASL username
    # - kafka-credentials/password: Kafka SASL password
    # - smtp-credentials/password: SMTP password for email notifications
    # - better-auth/secret: Better Auth JWT secret

scopes:
  - backend
  - recurring-task-service
  - notification-service
