apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kubernetes-secrets
  namespace: default
spec:
  type: secretstores.kubernetes
  version: v1
  metadata:
    # Kubernetes Secrets configuration (for Minikube deployment)
    # Secrets are stored as Kubernetes Secret resources in the cluster

    # No metadata required - Dapr automatically connects to Kubernetes API
    # Secrets accessed via secret name and key

    # Example secret structure:
    # apiVersion: v1
    # kind: Secret
    # metadata:
    #   name: database-credentials
    # type: Opaque
    # stringData:
    #   connection-string: "postgresql://user:password@localhost:5432/todos"
    #   statestore-connection-string: "postgresql://user:password@localhost:5432/todos"

scopes:
  - backend
  - recurring-task-service
  - notification-service
