/**
 * ChatKit Widget Component
 *
 * Integrates OpenAI ChatKit with Next.js 16 frontend
 * Features:
 * - Custom backend integration (not OpenAI hosted workflow)
 * - Better Auth JWT token authentication
 * - User-specific chat endpoint per authenticated user
 * - Automatic loading/auth state handling
 */

"use client";

import { useChatKit, ChatKit } from "@openai/chatkit-react";
import { useEffect, useState } from "react";
import { authClient } from "@/lib/auth";
import { cn } from "@/lib/utils";

interface ChatKitWidgetProps {
  /**
   * Optional custom API URL
   * If not provided, uses NEXT_PUBLIC_CHATKIT_API_URL from environment
   */
  apiUrl?: string;

  /**
   * Optional domain key (required for production)
   * If not provided, uses NEXT_PUBLIC_OPENAI_DOMAIN_KEY from environment
   */
  domainKey?: string;

  /**
   * Optional CSS class name for styling
   */
  className?: string;
}

/**
 * ChatKit Widget Component
 *
 * This component:
 * 1. Checks user authentication via Better Auth
 * 2. Gets JWT token using Better Auth's JWT plugin (authClient.token())
 * 3. Configures ChatKit to point to custom backend
 * 4. Renders chat interface with JWT authentication
 *
 * Configuration:
 * - api.url: Points to backend /api/chatkit endpoint
 * - Custom fetch: Adds JWT Authorization header
 * - domainKey: Frontend domain key for ChatKit
 *
 * JWT Token:
 * - Generated by Better Auth's JWT plugin
 * - Signed with EdDSA/RS256 algorithm
 * - Includes 'kid' header for JWKS verification
 * - Compatible with backend's JWKS-based verification
 */
export default function ChatKitWidget({
  domainKey,
  className = "",
}: ChatKitWidgetProps) {
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [userId, setUserId] = useState<string | null>(null);
  const [jwtToken, setJwtToken] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Get environment variables
  const chatkitDomainKey = domainKey || process.env.NEXT_PUBLIC_OPENAI_DOMAIN_KEY;

  /**
   * Check authentication and get JWT token on mount
   */
  useEffect(() => {
    async function checkAuth() {
      try {
        setIsLoading(true);
        setError(null);

        // Get session from Better Auth
        const session = await authClient.getSession();

        if (!session?.data?.user) {
          setIsAuthenticated(false);
          setIsLoading(false);
          return;
        }

        const user = session.data.user;
        setUserId(user.id);
        setIsAuthenticated(true);

        // Get JWT token from Better Auth using the JWT client plugin
        // This uses Better Auth's native token() method which generates
        // EdDSA/RS256 tokens with 'kid' header compatible with JWKS verification
        try {
          const tokenResult = await authClient.token();

          if (tokenResult.data?.token) {
            setJwtToken(tokenResult.data.token);
          } else if (tokenResult.error) {
            console.error("Better Auth token error:", tokenResult.error);
            setError("Failed to get authentication token");
          } else {
            console.error("No token in Better Auth response:", tokenResult);
            setError("Failed to get authentication token");
          }
        } catch (tokenError) {
          console.error("JWT token error:", tokenError);
          setError("Failed to get authentication token");
        }

        setIsLoading(false);
      } catch (err) {
        console.error("ChatKit auth check error:", err);
        setError("Failed to check authentication");
        setIsAuthenticated(false);
        setIsLoading(false);
      }
    }

    checkAuth();
  }, []);

  /**
   * Render loading state
   */
  if (isLoading) {
    return (
      <div className={`flex items-center justify-center p-8 ${className}`}>
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-gray-900 dark:border-white mx-auto mb-4"></div>
          <p className="text-gray-600 dark:text-gray-400">Loading chat...</p>
        </div>
      </div>
    );
  }

  /**
   * Render authentication required state
   */
  if (!isAuthenticated) {
    return (
      <div className={`flex items-center justify-center p-8 ${className}`}>
        <div className="text-center">
          <p className="text-gray-600 dark:text-gray-400 mb-4">
            Please sign in to use the chat feature
          </p>
          <a
            href="/login"
            className="text-blue-600 dark:text-blue-400 hover:underline"
          >
            Go to Login
          </a>
        </div>
      </div>
    );
  }

  /**
   * Render error state
   */
  if (error) {
    return (
      <div className={`flex items-center justify-center p-8 ${className}`}>
        <div className="text-center">
          <p className="text-red-600 dark:text-red-400 mb-4">Error: {error}</p>
          <button
            onClick={() => window.location.reload()}
            className="text-blue-600 dark:text-blue-400 hover:underline"
          >
            Reload
          </button>
        </div>
      </div>
    );
  }

  /**
   * Render ChatKit widget (only if authenticated and has token)
   */
  if (!userId || !jwtToken) {
    return (
      <div className={`flex items-center justify-center p-8 ${className}`}>
        <div className="text-center">
          <p className="text-gray-600 dark:text-gray-400">
            Initializing chat...
          </p>
        </div>
      </div>
    );
  }

  // Render the actual ChatKit component
  return (
      <ChatKitWidgetInner
        jwtToken={jwtToken}
        chatkitDomainKey={chatkitDomainKey}
        className={className}
        onError={setError}
      />
  );
}

/**
 * Inner ChatKit component that only renders when auth is ready
 */
function ChatKitWidgetInner({
  jwtToken,
  chatkitDomainKey,
  className,
  onError,
}: {
  jwtToken: string;
  chatkitDomainKey?: string;
  className: string;
  onError: (error: string) => void;
}) {
  // Get API base URL from env or use default
  const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";

  /**
   * Configure ChatKit with custom backend and JWT auth

   */
  const chatkit = useChatKit({
    // Custom backend API configuration
    api: {
      // ChatKit endpoint (no user_id in URL - JWT handles authentication)
      url: `${API_BASE_URL}/api/chatkit`,

      // Domain key is ALWAYS required (use "local-dev" for development)
      domainKey: chatkitDomainKey || "local-dev",

      // Custom fetch function to add JWT token
      fetch: async (input: RequestInfo | URL, init?: RequestInit) => {
        const url = typeof input === 'string' ? input : input instanceof URL ? input.toString() : input.url;
        return fetch(url, {
          ...init,
          headers: {
            ...init?.headers,
            Authorization: `Bearer ${jwtToken}`,
          },
        });
      },
    },

    // Error handling
    onError: ({ error }) => {
      console.error("ChatKit error:", error);
      onError(error.message || "ChatKit encountered an error");
    },

  });

  return (
    <div className={cn("w-full h-full flex flex-col", className)}>
      <ChatKit control={chatkit.control} />
    </div>
  );
}
